### ISSUE TITLE
Python version compression not faithful to the original C

### ISSUE THREAD

**Issue by m-schubert** [unwind/python-lzjb#1]
I've been testing out this code against the original code, and noticed a minor difference. Specifically [this particular bit of `compress()`](https://github.com/unwind/python-lzjb/blob/2617f84d20495c6004e42a916b9133a924b058d7/lzjb.py#L115-L117):

``` python
for mlen in MATCH_RANGE:
    if src[pos + mlen] != src[cpy + mlen]:
         break
```

At the end of this loop, `mlen` is a maximum of MATCH_MAX - 1, or 65.

This is the original C code:

``` c
for (mlen = MATCH_MIN; mlen < MATCH_MAX; mlen++)
    if (src[mlen] != cpy[mlen])
        break;
```

At the end of the C loop, `mlen` is a maximum of MATCH_MAX, or 66.

This results in different compressions for the same data. I also notice that in the Python code, LEMPEL_SIZE has been made bigger to 1024, which also results in different compressed data.

I haven't yet had an issue with either the C or the Python not being able to decode each other's output data, but I am wondering if there is a situation where it could happen.

**Comment by unwind** [comment]
Hi!

Thanks for your feedback, that does indeed sound like a bug. I'll try and
look into it, but my available time is limited.

Great to hear that you've used this code at all, and even better that it's
working for you. That always makes me happy. :)

Not sure if my test code checks interoperability, but I think it does. I
think I never quite "got" the meaning of LEMPEL_SIZE, perhaps that deserves
a second look too.

Regards,

/Emil

**Comment by m-schubert** [comment]
No worries. Happy to submit a patch, but I don't fully understand the way the algorithm works, so I'm not actually certain of the implications of the bug.

Interestingly I get better compression from this Python version for my data that from the C version.

**Comment by unwind** [comment]
Hi!

I've finally found some time to look into this (semi-recently became a
parent, which has ... impacted the amount of free time I have for projects
like this).

I ran a quick test compressing the "gdb" binary on my Ubuntu system, and I
didn't find any instance in which the "mlen" loop computed a different
value.

Do you have some source file which you know compresses differently between
my Python code and the reference C implementation?

Also, the reference C code (at
https://raw.githubusercontent.com/joyent/illumos-joyent/master/usr/src/uts/common/fs/zfs/lzjb.c)
has LEMPEL_SIZE equal to 1024, so that's not something I've changed as far
as I can understand. Can you clarify that part?

Regards,

/Emil

**Comment by unwind** [comment]
Hi again.

Of course, I rushed through the testing and compared the wrong files. :) My
apologies.

You're entierly correct in that the loops generate different final values
for "mlen" sometimes, with Python going one further than C. I'll look at
fixing that, now.

Regards,

/Emil
